on:
  push:
    branches:
      - homework_1

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: Building
        run: |
          ./installgtest.sh
          cmake CMakeLists.txt
          make
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Testing
        run: |
          ls -al
          ./tests
