on:
  push:
    branches:
      - homework_1

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installs
        run: |
          sudo apt update
          sudo apt install valgrind
          sudo apt install cppcheck
          sudo apt-get install lcov
          git clone https://github.com/google/googletest.git -b release-1.11.0
          cd googletest
          mkdir build
          cd build
          cmake .. -DBUILD_GMOCK=OFF
          make
          sudo make install
          cd ../..
  build:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: Building
        run: |
          cmake CMakeLists.txt
          make
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Testing
        run:
          ./tests
